describe('template spec', () => {
    beforeEach (() => { 
      cy.fixture('EPIC3_DATA').then(function (EPIC3_DATA) {
        this.EPIC3_DATA = EPIC3_DATA
      }) 
    })
    it ('Archive Flow', function () {
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/Illuminator?service=Personalization&saml2=disabled')
        cy.get('#logonuidfield').type(this.EPIC3_DATA.login)
        cy.get('#logonpassfield').type(this.EPIC3_DATA.password)
        cy.get('.urBtnStdNew').click()  
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt')
        cy.wait(5000)
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt#/ProfilePage')
        cy.get('#__xmlview2--list-roles').find('li').contains("STREAMING_ENGINE_ADMIN_ITS")
        cy.wait(5000)
        cy.get('#__button0').click()
        cy.wait(5000)
        cy.get('#__tile4').click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').clear({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').type(this.EPIC3_DATA.Plant)
        cy.get('#__xmlview3--filterbar-archive-flows-btnGo-content').click()
        cy.get('#__xmlview3--table-archive-flows-tblBody').find('div').eq(3).click()
        cy.get('#__xmlview3--button-run-flow-manually-content').click()
        cy.get('#__xmlview3--messagestrip-run-flow-manually').contains(this.EPIC3_DATA.Message1)
        cy.get('#__button4-content').click()
        cy.wait(5000)
        cy.get('#__xmlview4--combobox-data-source-inner').type(this.EPIC3_DATA.Plant)
        cy.get('#__item82').click({force: true})
        cy.get('#__xmlview4--input-data-flow-name-inner').type(this.EPIC3_DATA.DataFlowName)
        cy.get('#__xmlview4--switch-compressed-textoff').click()
        cy.get('#__xmlview4--switch-enabled-handle').click()
        cy.get('#__button8-content').click()
        cy.get('#__button8-content').should('be.visible')
        cy.get('#__xmlview4--input-description-inner').type(this.EPIC3_DATA.Description)
        cy.get('#__xmlview4--combobox-datadestination-inner').type(this.EPIC3_DATA.DataDestination)
        cy.get('#__item122-content').click({force: true})
        cy.get('#__button8-content').click()
        cy.get('#__button1-inner').click()
        cy.get('#__xmlview3--table-archive-flows-tblBody').find('span').eq(12).click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview4--input-description-inner').type(this.EPIC3_DATA.Update)
        cy.get('#__button8-content').click()
        cy.get('#__button10-content').click({force: true})
        cy.wait(5000)
        cy.get('#__input0-table-change-messages-0-inner').type(this.EPIC3_DATA.UpdateDescription , {force: true})
        cy.get('#__button10-content').click({force: true})
        cy.get('#__button6-inner').click({force: true})
        cy.get('.sapMSLIDescriptionText').contains("Update Archive Flow")
        cy.wait(5000)
        //cy.get('#__button13-inner').click({force: true})
        cy.get('#__xmlview3--combobox-plant-inner').clear({force: true})
        cy.get('#__xmlview3--combobox-plant-inner').type(this.EPIC3_DATA.Plant)
        cy.get('#__xmlview3--filterbar-archive-flows-btnGo-content').click()
        cy.get('#__xmlview3--table-archive-flows-tblBody').find('span').eq(10).click({force: true})     
        cy.get('#__xmlview4--button-delete-content').click({force: true}) 
        // //cy.get('#__button14-content').click({force: true})
        cy.get('#__button17-content').click({force: true})
        cy.get('#__button0-inner').click()
        cy.get('#__xmlview1--panel-sap-mii-CollapsedImg').click()
        cy.get('#__xmlview1--page-launchpad-cont').scrollTo(0, 1000)
        cy.get('#__tile14').click({force: true})

    })
  })