describe('template spec', () => {
  beforeEach (() => { 
    cy.fixture('example').then(function (example) {
      this.example = example
    })
    
  })
  Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })
  
it ('Configure PLANT', function () {
    cy.visit('https://sapwdawsemea.pharma.aventis.com:9101/XMII/Illuminator?service=Personalization&saml2=disabled')
    cy.get('#logonuidfield').type(this.example.login)
    cy.get('#logonpassfield').type(this.example.password)
    cy.get('.urBtnStdNew').click()  
    cy.visit('https://sapwdawsemea.pharma.aventis.com:9101/XMII/CM/StreamingEngine/StreamingEngine/index.irpt')
    cy.wait(2000)
    // cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt#/ProfilePage') la
    // cy.get('#__xmlview2--list-roles').find('li').contains("STREAMING_ENGINE_ADMIN_ITS")
    // cy.wait(5000)
    // cy.get('#__button1').click() la
    cy.get('#__tile0-hdr-text').click()
    cy.wait(6000)
    cy.get('#__button2-content').click({force: true})
    cy.get('#__button7-content').click()
    cy.get('#__button7-content').should('be.visible')
    cy.get('#__xmlview3--input-plant-id-inner').type(this.example.PlantID)
    cy.get('#__xmlview3--input-plant-description-inner').type(this.example.PlantDescription)
    cy.get('#__xmlview3--input-max-query-retry-inner').type(this.example.MaxQuery)
    cy.get('#__xmlview3--input-max-queue-rowcount-retry-inner').type(this.example.MaxQueue)
    cy.get('#__xmlview3--input-max-tags-per-agent-inner').type(this.example.MaxTagPerAgent)
    cy.get('#__xmlview3--input-audit-log-retention-inner').type(this.example.AuditLog)
    cy.get('#__xmlview3--input-job-duration-inner').type(this.example.JobDuration)
    cy.get('#__xmlview3--input-max-tags-per-job-inner').type(this.example.MaxTagPerJob)
    cy.get('#__xmlview3--input-connection-timeout-inner').type(this.example.ConnectionTimeOut)
    cy.get('#__xmlview3--input-job-catchup-multiplier-inner').type(this.example.JobCatchUp)
    cy.get('#__xmlview3--input-success-queue-size-inner').type(this.example.SuccessQueue)
    cy.get('#__xmlview3--input-watch-pco-dest-name-inner').type(this.example.WatchPcoDest)
    cy.get('#__xmlview3--input-max-watch-data-capture-points-inner').type(this.example.MaxWatchDataCapturePoints)
    cy.get('#__xmlview3--input-max-watch-data-capture-days-inner').type(this.example.MaxWatchDataCaptureDays)
    cy.get('#__xmlview3--input-max-watch-data-viz-days-inner').type(this.example.MaxWatchDataVizDays)
    cy.get('#__xmlview3--input-semarchy-location-id-inner').type(this.example.LocationId)
    cy.get('#__button5-content').click({force: true})
    cy.wait(5000)
    cy.get('#__field0-I').type(this.example.MDMLocation , {force: true}) 
    cy.get('#__dialog0-table-rows-row0').find("td").eq(2).click({force: true})
    cy.get('#__button7-content').click({force: true})
    cy.wait(5000)
    cy.get('#__button2-content').click({force: true})
    cy.get('#__xmlview3--input-plant-id-inner').type(this.example.PlantID)
    cy.get('#__xmlview3--input-plant-description-inner').type(this.example.PlantDescription)
    cy.get('#__xmlview3--input-max-query-retry-inner').type(this.example.MaxQuery)
    cy.get('#__xmlview3--input-max-queue-rowcount-retry-inner').type(this.example.MaxQueue)
    cy.get('#__xmlview3--input-max-tags-per-agent-inner').type(this.example.MaxTagPerAgent)
    cy.get('#__xmlview3--input-audit-log-retention-inner').type(this.example.AuditLog)
    cy.get('#__xmlview3--input-job-duration-inner').type(this.example.JobDuration)
    cy.get('#__xmlview3--input-max-tags-per-job-inner').type(this.example.MaxTagPerJob)
    cy.get('#__xmlview3--input-connection-timeout-inner').type(this.example.ConnectionTimeOut)
    cy.get('#__xmlview3--input-job-catchup-multiplier-inner').type(this.example.JobCatchUp)
    cy.get('#__xmlview3--input-success-queue-size-inner').type(this.example.SuccessQueue)
    cy.get('#__xmlview3--input-watch-pco-dest-name-inner').type(this.example.WatchPcoDest)
    cy.get('#__xmlview3--input-max-watch-data-capture-points-inner').type(this.example.MaxWatchDataCapturePoints)
    cy.get('#__xmlview3--input-max-watch-data-capture-days-inner').type(this.example.MaxWatchDataCaptureDays)
    cy.get('#__xmlview3--input-max-watch-data-viz-days-inner').type(this.example.MaxWatchDataVizDays)
    cy.get('#__xmlview3--input-semarchy-location-id-inner').type(this.example.LocationId)
    cy.get('#__button5-content').click({force: true})
    cy.wait(200)
    cy.get('#__field1-I').type(this.example.MDMLocation , {force: true} ) 
    cy.get('#__dialog1-table-rows-row0').find("td").eq(2).click({force: true})
    cy.get('#__button7-content').click({force: true})  
    //cy.get('#__button6').click({force: true})
    //cy.get('#__item6-content').click({force: true})
   // cy.get('#__popover0-messageViewMessageDescriptionText').contains(this.example.Message)
    cy.get('#__button1-img').click()
    cy.wait(2000)
    cy.get('#__xmlview2--input-plant-id-inner').type(this.example.PlantID)
    cy.get('#__xmlview2--filterbar-plant-parameters-btnGo-inner').click()
    cy.get('#__xmlview2--table-plant-parameters-tblBody').find("td").eq(2).click({force: true})
    cy.get('#__xmlview3--input-plant-id-inner').type('TEST2' ,  {force: true} )
    cy.get('#__xmlview3--input-plant-id-inner').should('have.value' , 'TEST')
    cy.wait(2000)
    cy.get('#__xmlview3--input-plant-description-inner').clear().type(this.example.PlantDescription_Update)
    cy.get('#__xmlview3--input-max-query-retry-inner').clear().type(this.example.MaxQuery_Update)
    cy.get('#__xmlview3--input-max-queue-rowcount-retry-inner').clear().type(this.example.MaxQueue_Update)
    cy.get('#__xmlview3--input-max-tags-per-agent-inner').clear().type(this.example.MaxTagPerAgent_Update)
    cy.get('#__xmlview3--input-audit-log-retention-inner').clear().type(this.example.AuditLog_Update)
    cy.get('#__xmlview3--input-job-duration-inner').clear().type(this.example.JobDuration_Update)
    cy.get('#__xmlview3--input-max-tags-per-job-inner').clear().type(this.example.MaxTagPerJob_Update)
    cy.get('#__xmlview3--input-connection-timeout-inner').clear().type(this.example.ConnectionTimeOut_Update)
    cy.get('#__xmlview3--input-job-catchup-multiplier-inner').clear().type(this.example.JobCatchUp_Update)
    cy.get('#__xmlview3--input-success-queue-size-inner').clear().type(this.example.SuccessQueue_Update)
    cy.get('#__xmlview3--input-watch-pco-dest-name-inner').clear().type(this.example.WatchPcoDest_Update)
    cy.get('#__xmlview3--input-max-watch-data-capture-points-inner').clear().type(this.example.MaxWatchDataCapturePoints_Update)
    cy.get('#__xmlview3--input-max-watch-data-capture-days-inner').clear().type(this.example.MaxWatchDataCaptureDays_Update)
    cy.get('#__xmlview3--input-max-watch-data-viz-days-inner').clear().type(this.example.MaxWatchDataVizDays_Update)
    cy.get('#__button7-content').click()
    cy.get('#__button9-BDI-content').click({force: true})
    cy.get('#__input0-table-change-messages-0-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-1-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-2-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-3-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-4-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-5-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-6-inner').type(this.example.input , {force: true})
    cy.get('#ChangeMessage-cont').scrollTo(0, 700)
    cy.get('#__input0-table-change-messages-7-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-8-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-9-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-10-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-11-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-12-inner').type(this.example.input , {force: true})
    cy.get('#__input0-table-change-messages-13-inner').type(this.example.input , {force: true})
    cy.get('#__button9-BDI-content').click({force: true})
    cy.wait(5000)
    // cy.get('#__button4-img').click({force: true})
    // cy.get('#__item14-imgNav').click({force: true})
    // cy.get('#__popover1-messageViewMessageDescriptionText').contains('Plant information has been saved successfully')  
    // cy.visit('https://dsw-uat.sanofi.com/') la
    // cy.visit('https://uat-dmdg.auth.eu-west-1.amazoncognito.com/login?client_id=6joteloln0oqbj2tntu2fmi5h&response_type=code&scope=openid&redirect_uri=https%3A%2F%2Fdsw-uat.sanofi.com%2Fauth')
    // //cy.visit('https://dsw-uat.sanofi.com/auth?code=f33a526d-7e4c-4f0c-b5ab-c144e54cdfe8') la
})
 })
