describe('template spec', () => {
    beforeEach (() => { 
      cy.fixture('EPIC4_DATA').then(function (EPIC4_DATA) {
        this.EPIC4_DATA = EPIC4_DATA
      }) 
    })
    it ('Contextual Flow', function () {
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/Illuminator?service=Personalization&saml2=disabled')
        cy.get('#logonuidfield').type(this.EPIC4_DATA.login)
        cy.get('#logonpassfield').type(this.EPIC4_DATA.password)
        cy.get('.urBtnStdNew').click()  
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt')
        cy.wait(13000)
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt#/ProfilePage')
        cy.get('#__xmlview2--list-roles').find('li').contains("STREAMING_ENGINE_ADMIN_ITS")
        cy.wait(10000)
        cy.get('#__button0').click({force: true})
        cy.wait(6000)
        cy.get('#__tile5').click({timeout: 10000})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').clear({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').type(this.EPIC4_DATA.Plant)
        cy.get('#__xmlview3--filterbar-contextual-flows-btnGo-content').click()
        cy.wait(5000)
        cy.get('#__xmlview3--table-contextual-flows-tblBody').find('div').eq(6).click()
        cy.wait(1000)
        cy.get('#__xmlview3--button-run-flow-manually-content').click()
        cy.get('#__xmlview3--messagestrip-run-flow-manually').contains(this.EPIC4_DATA.Message1)
        cy.get('#__button4-content').click()
        cy.wait(5000)
        cy.get('#__xmlview4--combobox-data-source-inner').type(this.EPIC4_DATA.DataSource)
        cy.get('#__item112-content').click({force: true})
        cy.get('#__xmlview4--input-text-area-sql-query-inner').type(this.EPIC4_DATA.SqlQuery_3)
        cy.get('#__xmlview4--combobox-mii-transaction-arrow').click()
        cy.get('#__item123').click({force: true})
        cy.get('#__xmlview4--switch-compressed-handle').click()
        cy.get('#__xmlview4--switch-enabled-handle').click()
        cy.get('#__button9').click()
        cy.get('#__button9').should('be.visible')
        cy.get('#__xmlview4--input-data-flow-name-inner').type(this.EPIC4_DATA.DataFlowName)
        cy.get('#__xmlview4--input-description-inner').type(this.EPIC4_DATA.Description)
        cy.get('#__xmlview4--combobox-datadestination-arrow').click({force: true})
        cy.get('#__item137').click({force: true})
        cy.wait(5000)
        cy.get('#__button9-content').click()
        cy.wait(5000)
        cy.get('#__button6-inner').click({force: true})
        cy.get('.sapMSLIDescriptionText').contains(this.EPIC4_DATA.Message2)
        cy.get('#__button13').click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').clear({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').type(this.EPIC4_DATA.Plant)
        cy.get('#__xmlview3--filterbar-contextual-flows-btnGo-content').click()
        //cy.get('#__xmlview3--table-contextual-flows-tblBody').contains('TEST').click()
        cy.get('#__item28-__clone3-imgNav').click()
        cy.wait(5000)
        cy.get('#__button7-content').click()
        cy.wait(5000)
        cy.get('#button-close-content').click({force: true})
        cy.get('#__xmlview4--input-description-inner').type(this.EPIC4_DATA.Update)
        cy.get('#__button9-content').click()
        cy.get('#__button15-inner').click({force: true})
        cy.get('#__input0-table-change-messages-0-inner').type(this.EPIC4_DATA.Update2 , {force: true})
        cy.get('#__button15-inner').click({force: true})
        cy.wait(5000)
        cy.get('#__button6').click({force: true})
        cy.get('.sapMSLIDescriptionText').contains(this.EPIC4_DATA.Message3)
        cy.get('#__button13').click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').clear({force: true})
        cy.wait(5000)
        cy.get('#__xmlview3--combobox-plant-inner').type(this.EPIC4_DATA.Plant)
        cy.wait(5000)
        cy.get('#__xmlview3--filterbar-contextual-flows-btnGo-content').click()
        //cy.get('#__xmlview3--table-contextual-flows-tblBody').find('div').eq(5).click()
        cy.get('#__item28-__clone3-imgNav').click()
        cy.wait(5000)
        cy.get('#__xmlview4--button-delete-content').click()
        cy.wait(5000)
        cy.get('#__button17-content').click({force: true})
        cy.wait(5000)
        cy.get('#__button6').click()
        cy.get('.sapMSLIDescriptionText').contains(this.EPIC4_DATA.Message4)
        cy.get('#__button13').click({force: true})
        cy.get('#__button0-inner').click()
        cy.get('#__xmlview1--panel-sap-mii-CollapsedImg').click()
        cy.get('#__tile14').click({force: true})
    })
  })