describe('template spec', () => {
    beforeEach (() => { 
      cy.fixture('EPIC2_DATA').then(function (EPIC2_DATA) {
        this.EPIC2_DATA = EPIC2_DATA
      }) 
    })
    it ('Custom Query P1', function () {
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/Illuminator?service=Personalization&saml2=disabled')
        cy.get('#logonuidfield').type(this.EPIC2_DATA.login)
        cy.get('#logonpassfield').type(this.EPIC2_DATA.password)
        cy.get('.urBtnStdNew').click()  
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt')
        cy.wait(10000)
        cy.visit('https://sapwdawsemea.pharma.aventis.com:9102/XMII/CM/StreamingEngine/StreamingEngine/index.irpt#/ProfilePage')
        cy.get('#__xmlview2--list-roles').find('li').contains("STREAMING_ENGINE_ADMIN_ITS")
        cy.wait(9000)
        cy.get('#__button1').click()
        cy.wait(5000)
        cy.get('#__tile1').click()
        Cypress.on('uncaught:exception', (err, runnable) => {
          return false
        })
        cy.wait(5000)
        // cy.get('#__xmlview3--combobox-plant-inner').click({force: true}).clear().type(this.EPIC2_DATA.PlantComboBox)
        // cy.get('#__item32-content').click({force: true})
        cy.get('#__xmlview3--combobox-plant-arrow').click()
        cy.get('#__xmlview3--combobox-plant-popup-list-listUl>li').each(($e,index)=>{
          if ($e.text() === this.EPIC2_DATA.PlantComboBox) {
            cy.wrap($e).click({force: true})}
          })   
        cy.wait(5000)
        cy.get('#__xmlview3--filterbar-data-sources-btnGo-BDI-content').click()
        cy.wait(5000)
        cy.get('#__xmlview3--table-datasources-tblBody').find("td").eq(1).click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview4--button-sql-query-BDI-content').click()
        cy.wait(30000)
        cy.get('#table-sql-test-tblHeader').find('span').eq(1).should('have.css', 'color', 'rgb(0, 128, 0)')
        cy.get('#table-sql-test-tblHeader').find('span').eq(3).should('have.css', 'color', 'rgb(0, 128, 0)')
        cy.get('#table-sql-test-tblHeader').find('span').eq(5).should('have.css', 'color', 'rgb(0, 128, 0)')
        cy.get('#table-sql-test-tblHeader').find('span').eq(7).should('have.css', 'color', 'rgb(0, 128, 0)')
        cy.wait(5000)
        cy.get('#button-close-BDI-content').click({force: true})
        cy.wait(5000)

        cy.get('#__xmlview4--input-text-area-sql-query-inner').focus().clear()
        cy.get('#__xmlview4--input-text-area-sql-query-inner').type(this.EPIC2_DATA.SqlQuery_1)
        cy.get('#__xmlview4--button-sql-query-BDI-content').click()
        cy.get('#text-error-column-name').contains("FatalError")
        cy.wait(1000)
        cy.get('#button-close-BDI-content').click({force: true})
        cy.wait(5000)
        cy.get('#__xmlview4--input-text-area-sql-query-inner').focus().clear()
        cy.get('#__xmlview4--input-text-area-sql-query').type(this.EPIC2_DATA.SqlQuery_2)
        cy.get('#__xmlview4--button-sql-query-content').click()
        cy.wait(5000)
        // cy.get('#table-sql-test-tblHeader').find('span').eq(1).should('have.css', 'color', 'rgb(0, 128, 0)') 
        // cy.get('#table-sql-test-tblHeader').find('span').eq(3).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(5).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(7).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(9).should('have.css', 'color', 'rgb(128, 128, 128)')
        // cy.wait(1000)
        // cy.get('#button-close-content').click({force: true})
        // cy.get('#__button0-inner').click({force: true})
        // cy.wait(5000)
        // cy.get('#__tile5').click({force: true})
        // cy.get('#__xmlview5--combobox-plant-inner').click({force: true})
        // cy.wait(6000)
        // cy.get('#__xmlview5--combobox-plant-inner').clear()
        // cy.wait(5000)
        // cy.get('#__xmlview5--combobox-plant-inner').type("Geel")
        // cy.wait(5000)
        // cy.get('#__xmlview5--filterbar-contextual-flows-btnGo-inner').click()
        // cy.get('#__xmlview5--table-contextual-flows-tblBody').find("tr").eq(2).click({force: true})
        // cy.get('#__xmlview6--input-text-area-sql-query-inner').focus().clear().click()
        // cy.get('#__xmlview6--input-text-area-sql-query-inner').type(this.EPIC2_DATA.SqlQuery_3)
        // cy.get('#__button13-content').click()
        // cy.wait(6000)
        // cy.get('#table-sql-test-tblHeader').find('span').eq(1).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(3).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(5).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(7).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(9).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(11).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(13).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(15).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(17).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(19).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(21).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(23).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(25).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(27).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(29).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(31).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(33).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(35).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(37).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(39).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(41).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(43).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.wait(5000)
        // cy.get('#button-close-content').click({force: true})
        // cy.get('#__button1-inner').click()
        // cy.get('#__xmlview5--table-contextual-flows-tblBody').find("tr").eq(1).click({force: true})
        // cy.get('#__xmlview6--input-text-area-sql-query-inner').scrollTo(0, 700).click()
        // cy.wait(5000)
        // cy.get('#__xmlview6--input-text-area-sql-query-inner').type(this.EPIC2_DATA.Update_Sql)
        // cy.get('#__button15-content').click({force: true})
        // cy.wait(5000)
        // cy.get('#__input0-table-change-messages-0-inner').type(this.EPIC2_DATA.input , {force: true})
        // cy.get('#__button17-inner').click({force: true})
        // cy.wait(5000)
        // cy.get('#__button12-img').click()
        // cy.get('#__popover0-messageViewMessageDescriptionText').contains("Flow information has been updated successfully")
        // cy.get('#__button20-img').click({force: true})
        // // cy.get('#__xmlview5--combobox-plant-inner').click({force: true})
        // cy.get('#__xmlview5--combobox-plant-inner').clear()
        // cy.wait(5000)
        // // cy.get('#__xmlview5--combobox-plant-inner').type(this.EPIC2_DATA.PlantComboBox)
        // cy.get('#__xmlview5--combobox-plant-arrow').click()
        // cy.wait(5000)
        // cy.get('#__xmlview5--combobox-plant-popup-list-listUl>li').each(($e,index)=>{
        //   if ($e.text() === this.EPIC2_DATA.PlantComboBox) {
        //      cy.wrap($e).click({force: true})}
        //    })   
        // cy.wait(5000)
        // cy.get('#__xmlview5--filterbar-contextual-flows-btnGo-inner').click()
        // cy.wait(10000)
        // cy.get('#__xmlview5--table-contextual-flows-tblBody').find("tr").eq(1).click({force: true})
        // cy.wait(5000)
        // cy.get('#__xmlview6--button-test-transaction-content').click({force: true})
        // cy.get('#__xmlview6--datetimepicker-from-date-inner').type(this.EPIC2_DATA.StartDate , {force: true})
        // cy.get('#__xmlview6--datetimepicker-to-date-inner').click({force: true})
        // cy.get('#__xmlview6--datetimepicker-to-date-inner').type(this.EPIC2_DATA.ToDate , {force: true})      
        // cy.get('#__button24-content').click({force: true})
        // cy.get('#__button23-content').click({force: true})
        // cy.get('#__button1-inner').click()
        // cy.wait(5000)
        // cy.get('#__xmlview5--table-contextual-flows-tblBody').find('div').eq(6).click({force: true})
        // cy.get('#__xmlview5--button-enable-data-upload-content').click()
        // cy.get('#historical-upload-time-from-inner').type(this.EPIC2_DATA.StartDateHistorical , {force: true}) 
        // cy.get('#historical-upload-time-to-inner').type(this.EPIC2_DATA.EndDate , {force: true})
        // cy.get('#historical-upload-max-timeframe-inner').clear({force: true})
        // cy.get('#historical-upload-max-timeframe-inner').type(this.EPIC2_DATA.Time , {force: true})
        // cy.get('#historical-upload-save-content').click({force: true})
        // cy.get('#historical-load-close-content').click({force: true})
        // cy.get('#__button12-img').click()

        //here
        // cy.get('.sapMSLIDescriptionDiv').contains('Historical Data Upload')
        // cy.get('#__button20-inner').click({force: true})
        //fin ici 
        // cy.get('#__xmlview5--table-contextual-flows-tblBody').find("tr").eq(1).click({force: true})
        // cy.get('#__button13-content').click()
        // cy.wait(5000)
        // cy.get('#table-sql-test-tblHeader').find('span').eq(1).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(3).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(5).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(7).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(9).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(11).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(13).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(15).should('have.css', 'color', 'rgb(0, 128, 0)')
        // cy.get('#table-sql-test-tblHeader').find('span').eq(17).should('have.css', 'color', 'rgb(255, 0, 0)')
        // cy.wait(1000)
        // cy.get('#button-close-content').click({force: true})

    })
    //it ('Create Data Source', function () {    
        // cy.get('#__button4-content').click()
        // cy.get('#__xmlview4--combobox-plant').type(this.EPIC2_DATA.Plant)
        // cy.get('#__item27-__xmlview4--combobox-plant-4').click({force: true})
        // cy.get('#__xmlview4--switch-enabled-textoff').click()
        // cy.get('#__xmlview4--input-data-source-name-inner').type(this.EPIC2_DATA.DataSourceName)
        // cy.get('#__xmlview4--combobox-dataserver-process-inner').type(this.EPIC2_DATA.DataServerProcess)
        // cy.get('#__item28-__xmlview4--combobox-dataserver-process-11').click({force: true})
        // cy.get('#__xmlview4--combobox-dataserver-contextual').type(this.EPIC2_DATA.DataServerContextual)
        // cy.get('#__item31-__xmlview4--combobox-dataserver-contextual-33').click({force: true})
        // cy.get('#__xmlview4--combobox-dataserver-contextual-type-inner').type(this.EPIC2_DATA.TypeContextual)
        // cy.get('#__item32').click({force: true})
        // cy.get('#__xmlview4--input-description-inner').type(this.EPIC2_DATA.Description)
        // cy.get('#__xmlview4--input-pco-server-url-inner').type(this.EPIC2_DATA.PcoServerUrl)
        // cy.get('#__xmlview4--combobox-pco-credential-inner').type(this.EPIC2_DATA.PcoCredential)
        // cy.get('#__item35-__xmlview4--combobox-pco-credential-6').click({force: true})
        // cy.get('#__xmlview4--switch-contextual-handle').click()
        // cy.get('#__xmlview4--switch-batch-information-enabled-handle').click()
        // cy.get('#__xmlview4--combobox-batch-source-system-inner').type(this.EPIC2_DATA.BatchSource)
        // cy.get('#__item36-__xmlview4--combobox-batch-source-system-0').click({force: true})
        // cy.get('#__xmlview4--input-batch-source-equipment-level-inner').type(this.EPIC2_DATA.Level)
        // cy.get('#__xmlview4--input-text-area-sql-query-inner').type(this.EPIC2_DATA.SqlQuery)
        // cy.get('#__xmlview4--button-sql-query-content').click()
        // cy.wait(5000)
        // cy.get('#button-close-content').click({force: true})
        // cy.get('#__button8-content').click()  
        
   // })

  })